### ISSUE TITLE
error cuModuleLoad1-218

### ISSUE THREAD

**Issue by stantonhive** [Etayson/Etarkangaroo#1]
Hi, I ran into a problem at startup (puzzle 125)
"error cuModuleLoad1-218"
GPU code #ND128

Command: Etarkangaroo -dp 16 -wf htwork -kf kangaroowork -o result.txt -wi 300 -wsplit -wmerge -rb 10000000000000000000000000000000 -re 1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -pub 0233709EB11E0D4439A729F21C2C443DEDB727528229713F0065721BA8FA46F00E
![Screenshot_5](https://github.com/Etayson/Etarkangaroo/assets/49280269/9bf61cde-3e5e-46ac-a525-84c7d65b5986)

RTX3060 
Etar pls help me)

**Comment by Etayson** [comment]
Try now. Reload release 2.2 PTX for driver >=12 replaced.
-dp 16 for range 2^124 is to low,  need at least 29 (around 600Gb hashtable)
and try to play with -grid 84,256 or 84,128 or 56,256 to get best speed

**Comment by stantonhive** [comment]
> Попробуйте сейчас. Перезагрузите версию 2.2 PTX для замены драйвера >= 12. -dp 16 для диапазона 2 ^ 124 слишком низкий, требуется как минимум 29 (хэш-таблица объемом около 600 Гб) и попробуйте поиграть с -grid 84,256 или 84,128 или 56,256, чтобы получить максимальную скорость

Thanks Etar, everything works great!

**Comment by stantonhive** [comment]
Can I ask you to write the optimal parameters for 8x3070ti? And what parameters should I increase?

**Comment by Etayson** [comment]
The -grid parameter consists of 2 parts block size and thread size for every selected GPUs
3070 ti have 48mp so block size must be a multiple of 48 for ex. 96 or 144
Thread size 256 is optimal for this GPU.
try -grid 96,256,96,256,96,256,96,256,96,256,96,256,96,256,96,256
or -grid 144,256....

**Comment by stantonhive** [comment]
> The -grid parameter consists of 2 parts block size and thread size for every selected GPUs 3070 ti have 48mp so block size must be a multiple of 48 for ex. 96 or 144 Thread size 256 is optimal for this GPU. try -grid 96,256,96,256,96,256,96,256,96,256,96,256,96,256,96,256 or -grid 144,256....

15488 mk\s) Thanks, Etar)

**Comment by stantonhive** [comment]
Still do not quite understand about -dp ? which range is better to use? I plan to increase the power in x10
