### ISSUE TITLE
error cuMemcpyHtoD-719

### ISSUE THREAD

**Issue by stantonhive** [Etayson/Etarkangaroo#2]
Can you please tell me what could be the cause of this error? "error cuMemcpyHtoD-719"  this platform worked in conjunction with the server

**Comment by Etayson** [comment]
What GPUs are you using? Show your start parametrs for kangaroo and screenshot with issue to get more info.

**Comment by stantonhive** [comment]
EtarkangarooClient.exe -pool ххх.хххх.хххх:8000 -d 0,1,2,3,4,5,6,7 -grid 92,256,92,256,92,256,92,256,92,256,92,256,92,256,92,256 -wi 300 -wmerge -min 1 

I can not send a screenshot, I have already restarted the system. But I can roughly describe, previously there were settings "saving a file every 50 minutes", the error appeared after some time. I mean that I just didn't have enough RAM. By changing the settings to save every 5 minutes, the problem seems to have disappeared. Now I'm testing. But thanks anyway for your answer. If I manage to solve it faster than the miners, the reward will be waiting for you. I don’t really understand how the server works, and how to connect clients correctly. I described the problem in the next topic which is related to the server.

**Comment by Etayson** [comment]
ok, if the problem persists, try to take a screenshot to help solve the problem. I used -wi 21600 (save every 6 hours) and had no problems with it.

**Comment by stantonhive** [comment]
> ok, if the problem persists, try to take a screenshot to help solve the problem. I used -wi 21600 (save every 6 hours) and had no problems with it.

Thank you for the detailed answer. I would be grateful for your answer in the next topic about the server.

**Comment by stantonhive** [comment]
the topic is closed, the questions in this section have been exhausted. Thanks to the developer.
