### ISSUE TITLE
error cuModuleLoad1-218,  GTX 1080 Ti  (28x64)=>(56x128)

### ISSUE THREAD

**Issue by ghost** [Etayson/Etarkangaroo#4]
Hi Etar,
I try with 56,128 84,256 or 84,128 or 56,256 GTX 1080 Ti . still not work, looking for your help.
Etarkangaroo.exe -dp 16 -d 0 -grid 56,128 -wf htwork -kf kangaroowork -o result.txt -wi 300 -wsplit -wmerge -rb 8000000000000000 -re ffffffffffffffff -pub 03100611c54dfef604163b8358f7b7fac13ce478e02cb224ae16d45526b25d9d4d
![2](https://github.com/Etayson/Etarkangaroo/assets/42763020/157cee75-22e7-441d-acf1-41ee2039e74c)

**Comment by Etayson** [comment]
The program supports video cards with architecture SM (ARCH)>=75
1080ti uses architecture SM (ARCH) = 61
You not first who try to launch old card, so i will publish release 2.3 that will support SM (ARCH)>=35
P.S. release already published.

**Comment by ghost** [comment]
> The program supports video cards with architecture SM (ARCH)>=75 1080ti uses architecture SM (ARCH) = 61 You not first who try to launch old card, so i will publish release 2.3 that will support SM (ARCH)>=35 P.S. release already published.

it worked, thanks.
